// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieometcnavaklzstipfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb21ldGNuYXZha2x6c3RpcGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDk2NTEsImV4cCI6MjA2MzY4NTY1MX0.szjelskZ4YIpXnKElhEM8u6R8k1p4F5l91PfaJh0Cfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);